// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about-us": {
    params: {};
  };
  "/owner": {
    params: {};
  };
  "/owner/:booking": {
    params: {
      "booking": string;
    };
  };
  "/owner/register": {
    params: {};
  };
  "/login": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about-us" | "/owner" | "/owner/:booking" | "/owner/register" | "/login";
  };
  "./presentation/common/layouts/BaseLayout.tsx": {
    id: "presentation/common/layouts/BaseLayout";
    page: "/" | "/about-us" | "/owner" | "/owner/:booking" | "/owner/register";
  };
  "./pages/HomePage.tsx": {
    id: "pages/HomePage";
    page: "/";
  };
  "./pages/BrowsePage.tsx": {
    id: "pages/BrowsePage";
    page: "/about-us";
  };
  "./pages/owner/home.tsx": {
    id: "pages/owner/home";
    page: "/owner";
  };
  "./pages/owner/booking.tsx": {
    id: "pages/owner/booking";
    page: "/owner/:booking";
  };
  "./pages/owner/register.tsx": {
    id: "pages/owner/register";
    page: "/owner/register";
  };
  "./presentation/common/layouts/AuthLayout.tsx": {
    id: "presentation/common/layouts/AuthLayout";
    page: "/login";
  };
  "./presentation/auth/ui/pages/LoginPage.tsx": {
    id: "presentation/auth/ui/pages/LoginPage";
    page: "/login";
  };
};